name: Angular - Hello world - Quick Start - Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bitsrc/nightly:latest
    env:
      HOME: /home/bituser
    steps:
      - name: Update BVM
        run: |
          bvm config set RELEASE_TYPE nightly
          bvm upgrade
          bvm config
          bit --version
      - name: Initialize a workspace
        run: |
          bit new hello-world-angular my-hello-world-angular --env teambit.community/starters/hello-world-angular --log error
      - name: Run the app component
        run: |
          cd my-hello-world-angular
          bit run hello-world-app --log error &
          checkserver http://localhost:3000
      - name: Preview components
        run: |
          cd my-hello-world-angular
          bit start --log error &
          checkserver http://localhost:3000
      - name: Collaborate
        run: |
          cd my-hello-world-angular
          bit status --log error
      - name: Create a local scope, compile and export
        run: |
          barescope my-org.my-scope-name my-hello-world-angular
          cd my-hello-world-angular
          bit scope rename org.scope-name my-org.my-scope-name --refactor --log error
          bit link --log error
          bit compile --log error
          bit tag --message "initial tag" --log error
          bit export --log error
